# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('course', models.CharField(choices=[('V', 'VOKAL'), ('T', 'THEATER')], max_length=5)),
                ('formc', models.IntegerField(choices=[(9, 9), (10, 10), (11, 11)])),
                ('partc', models.CharField(choices=[('FM', 'FM'), ('CHE', 'CHE')], max_length=3)),
            ],
        ),
    ]
