# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('V', 'Вокал'), ('T', 'Театр')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='partc',
            field=models.CharField(choices=[('FM', 'ФМ'), ('CHE', 'ХИМ')], max_length=3),
        ),
    ]
