# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161208_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='formc',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='partc',
            new_name='part',
        ),
    ]
